- hosts: localhost
  tasks:
        - ec2:
                aws_access_key: "AKIAJJTYODWANZ5RBO5A"  
                aws_secret_key: "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"
                instance_ids: "i-01ad14aff893355a2"
                region: 'ap-south-1'
                state: stopped
                wait: yes
                vpc_subnet_id: "subnet-9728aadb"
                assign_public_ip: no
  
